### ISSUE TITLE
Populate reference data matrix

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/htsinfer#100]
**Is your feature request related to a problem? Please describe.**

We have recently started collecting reference data for rigorously testing HTSinfer in [this matrx](https://docs.google.com/spreadsheets/d/1r4QolWT3uFnmAVTyGrcNnVEy78-4j446-S44jogxx5I/edit). In order to check the performance/reliability, we would need a lot more data sets and associated metadata, covering
- a range of diverse organisms from different clades of the phylogentic tree (among the supported organisms; can be obtained by parsing the [set of ribosomal transcripts](https://github.com/zavolanlab/htsinfer/raw/dev/data/transcripts.fasta.gz)) 
- different sequencing depths (<1 mio to >10 mio)
- different read lengths (35 - 200 nt)
- different read orientations
- single-/paired-ended libraries

Note that we do not need all possible combinations of those different parameters - just a good general coverage to have at least a small number of samples per organism and for each of the categories (single/paired) and extremes (small/big libraries, short/long reads).

**Describe the solution you'd like**

- Search/query the [SRA](https://www.ncbi.nlm.nih.gov/sra) for data sets of interest (i.e., small/big ones, short/longs reads, different organisms)
- Shortlist data sets that have one or more publications associated
- Mine the relevant metadata from SRA and the associated publications and enter into the list

Note that the library source/organism and whether a library is single- or paired-ended should be recorded in the SRA metadata. However, 3'-adapters are, if at all, usually only described in the methods sections of associated papers. Library orientations are not usually recorded at all, but can be determined if the name of the kit that was used to prepare the library is provided (kits generally use the same library orientation), by reading the kit instructions. This may also shed light on the sequence of the 3'-adapters used.

For that reason, it is probably a good idea to add a "Sequencing kits" tab to the reference data spreadsheet in which the library orientation (and possibly adapters) for the different kits can be recorded. In that way, we have to check each kit manual only once.

Note that this is an ongoing issue that can easily be addressed by multiple people without risk of conflicts/overlaps.

**Comment by BorisYourich** [comment]
From the 400-something species that are in the set of ribosomal transcripts I have created clusters based on taxonomical rank "class" to obtain the most diverse subset of species and picked one from each of the 50 cluster and mined the SRA for experiments which are Single-end, Paired-end and from one interval of the specified lengths(<30,<80, <130, <180). I obtained +300 results, from which only 83 had a pubmed-id associated with them, those are the records that I appended into the [HTSinfer test data table](https://docs.google.com/spreadsheets/d/1r4QolWT3uFnmAVTyGrcNnVEy78-4j446-S44jogxx5I/edit). I didn't yet go through the publications, maybe it would be nice if some other pair of eyes checks it, anyway no problem for me to search for library and adapter info in the publications, just not sure wether we need so many test datasets, or should we want more perhaps?

**Comment by uniqueg** [comment]
Awesome job @BorisYourich!

Actually, we were planning to spend an afternoon session with 10 people or so mining, so that the work isn't so dull on any one person. Your work is absolutely perfect for that, because all we need to do is go through the publications and check for the info we need (sequencing kit, most importantly, or adapter, length, orientation directly, if available).

FYI @mzavolan

**Comment by BorisYourich** [comment]
Alright, I am happy you like it :smiley: glad to have helped, good luck with mining the publications :+1:

**Comment by uniqueg** [comment]
Looking at the list of organisms that you ended up sampling, I thought that maybe we could also have some more representation by the more common organisms and closely related species. Would it be easy for you to go through the same selection process for a given list of species?

If so, could you do this for the following?

```console
# primates
cjacchus
hsapiens
mmulatta
pabelii
panubis
ppaniscus
ptroglodytes

# livestock
btaurus
chircus
ecaballus
ggallus
oaries
sscrofa

# rodents
cporcellus
mauratus
mmmarmota
mmusculus
ocuniculus
rnorvegicus

# fungi
pmexicana
scervisiae
spombe

# plants
athaliana
bvulgaris
cjaponica
osativa
zmays

# worms
celegans
cbriggsae

# fish
drerio
olatipes
xmaculatus

# insects
amellifera
bmori
dmelanogaster

# amphibians & reptiles
acarolinensis
xtropicalis
```

**Comment by BorisYourich** [comment]
Sure no problem, though I won’t manage today. Hopefully tomorrow it will be ready.

**Comment by uniqueg** [comment]
Great. Tomorrow is totally fine. In fact, the earliest we will need it is next Friday.

**Comment by uniqueg** [comment]
Ah, before I forget: We kinda need the SRR identifiers of the actual libraries. We can easily get them from the SRX identifiers, so no need to change that for the available ones. But if it's easy to include them for the new ones, then it would be good to include them.

**Comment by uniqueg** [comment]
@BorisYourich: did you have a chance to look at this?

**Comment by BorisYourich** [comment]
Hey, I am sorry I didn’t collect all the samples yet, had a very hectic two weeks with onboarding on the new project, though I dedicated tommorow to this project, will run the mining scripts and share all the results.

**Comment by uniqueg** [comment]
I think we have done this, no, @balajtimate? I will close it, please re-open if you think it's not solved.
