### ISSUE TITLE
Compile a list of common model organisms to retrieve test samples for

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/htsinfer#105]
Include the following:

- Classical model organisms (human, mouse, rat, yeast, zebrafish, worm, fruit fly, frog)
- Domesticated animals (cat, dog, horse, cow, pig, goat)

Try to find, for each family of organims, also one or two closely related organisms, preferring the more common ones.
Pick only organisms that are in `data/transcripts.fasta.gz`.

Once the list is assembled, pass to @BorisYourich for inclusion in the retrieval script.

**Comment by balajtimate** [comment]
A list of organisms already compiled can be found [in this comment.](https://github.com/zavolanlab/htsinfer/issues/100#issuecomment-1405175966)
