### ISSUE TITLE
Add missing known adapters to adapters file

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/htsinfer#106]
From the test sample matrix, we know a few adapters that _should_ be in the data but were not found. This is likely because these adapter (fragments) are not included in `data/adapter_fragments.txt`.

Also, from sourcing the kits for the list of test samples, and by going through the kits, we might a few othe adapters that are not yet in the list.

Finally, have a search online to see if similar lists/resources exist, e.g., this [repo for small RNA adapters](https://github.com/joey0214/adapter4srna) and official resources like [this](https://dnatech.genomecenter.ucdavis.edu/wp-content/uploads/2019/03/illumina-adapter-sequences-2019-1000000002694-10.pdf) and [this](https://emea.support.illumina.com/downloads/illumina-adapter-sequences-document-1000000002694.html).

Add all known, missing adapter fragments (starting at 5' adapter and using only 15 nts) to `data/adapter_fragments.txt`.

**Comment by balajtimate** [comment]
The only additional one (`AGATCGGAAGAGCAC`) I could find was added to the `adapter_fragments.txt`. It was inferred from one of the samples but can also be found in the Illumina guide. All other fragments from the guide and from other sources were already in the fragments list.
I'll rerun the test with the added fragment and the higher sample count and see what comes up.
