### ISSUE TITLE
Extract a subset of random reads from a fastq file

### ISSUE THREAD

**Issue by mzavolan** [zavolanlab/htsinfer#11]
To speed up inferences about read architecture in a library, extract a subset of reads (default all). Should take as parameters the number or proportion of reads to be extracted and should take into account that the reads may or may not be sorted alphabetically.

**Comment by uniqueg** [comment]
Note that for scalability and the typical sizes of the files we will be dealing with, reading the entire file into memory is not a great/scalable solution. On the other hand, opening/closing the file repeatedly for every line/entry you want to pick will be _very_ slow. Try to come up with a solution that does _not_ load the file into memory and does _not_ open/close the file more than twice (it will probably be hard/impossible to do it with just one pass).
