### ISSUE TITLE
STAR fails to create index

### ISSUE THREAD

**Issue by balajtimate** [zavolanlab/htsinfer#115]
This might not be directly related to HTSinfer itself, but when running HTSinfer on my PC with the samples [SRR19067720](https://www.ncbi.nlm.nih.gov/sra/?term=SRR19067720) and [SRR12414066](https://www.ncbi.nlm.nih.gov/sra/?term=SRR12414066), the process terminates and I get the error message 'Failed to create STAR index'. Both samples are from the same organism Pongo abelii (even though the size of the samples are very different, 6.5 GB vs 166 MB), which I suppose is not a frequent model organism, but it also happened with a human sample too, when I used the `--records` set to default. 

It's probably a memory issue, because the termination happens after throwing an instance of `std::bad_alloc`; also, it doesn't seem to happen when running HTSinfer on the cluster.

I'm just brining this up because it could potentially arise when other end-users run it on their own setup (and not on a cluster).
Maybe we could just add a minimum memory recommendation in the readme?

**Comment by uniqueg** [comment]
I'm a bit confused. Aren't we building the same index, regardless of the source organism and the sample? 🤔

**Comment by balajtimate** [comment]
There's actually three samples with the same organism, `SRR10393299`, `SRR12414066` and `SRR19067720`. When I run them on my PC, there's the 'Failed to create STAR index' error, so I ran them on the cluster, and this time the index is created and the error is at the alignment step:

```
[2023-04-04 17:23:19 DEBUG] Processing SAM file: '/scratch/balajt0000/slurm-job.25928198/tmp_htsinfer/tmp_FZ031/alignments/file_1/Aligned.out.sam'
[W::sam_hdr_create] Duplicated sequence "RPS2|YGL123W|YGL123W_mRNA|scerevisiae|4932" in file "/scratch/balajt0000/slurm-job.25928198/tmp_htsinfer/tmp_FZ031/alignments/file_1/Aligned.out.sam"
[W::sam_hdr_create] Duplicated sequence "RPS3|YNL178W|YNL178W_mRNA|scerevisiae|4932" in file "/scratch/balajt0000/slurm-job.25928198/tmp_htsinfer/tmp_FZ031/alignments/file_1/Aligned.out.sam"
[W::sam_hdr_create] Duplicated sequence "RPS5|YJR123W|YJR123W_mRNA|scerevisiae|4932" in file "/scratch/balajt0000/slurm-job.25928198/tmp_htsinfer/tmp_FZ031/alignments/file_1/Aligned.out.sam"
[E::sam_hrecs_update_hashes] Duplicate entry "RPS2|YGL123W|YGL123W_mRNA|scerevisiae|4932" in sam header
[E::sam_parse1] failed to parse header
[W::sam_read1_sam] Parse error at line 10463
[2023-04-04 17:23:19 ERROR] FileProblem: Failed to open SAM file: '/scratch/balajt0000/slurm-job.25928198/tmp_htsinfer/tmp_FZ031/alignments/file_1/Aligned.out.sam'
```

I checked and the organism `pabelii` is in the `data/transcript.fasta.gz` so the organism is not the issue.

**Comment by uniqueg** [comment]
First of all, it's really weird that you would be getting different results locally and on the node. Some questions:
- Are you sure the same version of STAR is being used in both cases?
- Do you get the same behavior if you only execute the respective STAR commands (index generation and mapping), without them being wrapped by Snakemake?

That being said, the issue seems to be a duplicate sequence in the header, which may possible be a result of corruption of the transcripts file (multiple entries for yeast `RPS2`). But not sure why this occurs only for _these_ samples.

Anyway, maybe this could help: https://www.biostars.org/p/81520/
Or other search results when googling for that specific error...

**Comment by balajtimate** [comment]
> I'm a bit confused. Aren't we building the same index, regardless of the source organism and the sample? 🤔

As it turns out, there is actually a filtering step based on the inferred _organism_, so the size of reference and SA pre-indexing string size for STAR changes every run. If no organism is getting inferred, STAR uses `Size of reference: 9290472` and `SA pre-indexing string size: 10` for the indexing step, and that's what causes the memory issue, as the number of references is too large. In this case, `--genomeChrBinNbits` should be reduced to reduce RAM consumption. The scaling for this can be calculated as `min(18,log2[max(GenomeLength/NumberOfReferences,ReadLength)])`. 

I'll add this to the `create_star_index` function in `htsinfer/get_read_orientation.py`.

**Comment by balajtimate** [comment]
So just to summarize:

- Added `--genomeChrBinNbits` to `get_read_orientation.py` to circumvent the memory issue which arises when no organism filtering happens, as well as optimizing the memory usage of STAR indexing.  
- As it turns out, running STAR with `--genomeChrBinNbits` set to different values, it also generates slightly different genome indices, especially the generated `index/Genome`, the genome reference sequences fasta files. I'm not yet entirely sure why this happens, but it results in different and fewer alignments in the next step, which caused the test files `paired_isf`, `paired_isr` and `paired_iu` to not get their orientation inferred.
- By changing the default of `--read-orientation-min-mapped-reads` to 18, which sets the minimum number of mapped reads for deeming the read orientation result to be reliable, we can avoid this issue, as there's 18 mapped reads in the test samples with the calculated `--genomeChrBinNbits` setting. 

I know this is not a perfect solution, but I think when running it on normal samples, 18 vs 20 min mapped reads don't really make a difference, but I'll run it again on our test samples of 770, to see if the inferred orientation changes.
