### ISSUE TITLE
Randomize nucleotide sequences

### ISSUE THREAD

**Issue by mzavolan** [zavolanlab/htsinfer#12]
Given a set of input sequences, generate randomized variants using a markov process. The order of the markov chain to be considered is a parameter. More concretely, we want to generate shuffled variants of the initial sequences that are similar in some way, but are not constructed to contain specific adaptor/barcode motifs. The simplest way to generate such variant sequences is to *shuffle* (permute the letters of) the input sequences. However, mammalian genes/genomes have some very distinct nucleotide composition biases such as being relatively depleted in CG dinucleotides (relative to the expected frequency of the dinucleotide given the frequencies of C's and G's), which, if ignored in the shuffling, will lead to the misestimation of frequencies of these motifs relative to the genome-average. To better preserve genome composition statistics in the shuffling, we would have to enforce that dinucleotide frequencies of the input sequences are maintained. An approximation that is simpler to implement is to maintain dinucleotide frequencies not strictly, but *on average*, which we can do by computing the frequencies of observing A,C,G,T following each of the A,C,G,T nucleotides and then generating as many and as long random sequences as the initial sequences, extending a sequence base by base, and choosing the next base given the current base and the probabilities we just mentioned.

Another parameter could be the number of sets of randomizations to generate.

**Comment by mischa-m** [comment]
Hi :) If possible, I would like to work on this issue.

**Comment by uniqueg** [comment]
Sure, assigned you :)

**Comment by ThomasMortelmans** [comment]
Hi, if possible, I would also like to work on this issue

**Comment by mischa-m** [comment]
Thomas and I wrote an outline and docstrings of the functions that we are trying to implement (below). It would be great if you could have a quick look and see if we are heading in the right direction. We thought that it might be a good idea to split up the main function into two separate functions, also to make it easier for us to work on the problem:

1. Read the input sequence and use it to generate a markov matrix.
2. Use this matrix and the length of the input string to generate a list of randomised sequences.

One question we ran into is, whether we can assume that the input string only contains the characters AGCT or if there can be other letters, e.g. in the case of ambiguity/ RNA/ etc. Then we would have to think about a solution to build the markov matrix dynamically.

Thanks for your feedback!

```python
import numpy as np

def randomize_nucleotide_sequence(input_sequence: str,
    number_random_seq: int = 1) -> list:
    """
    Returns randomised sequence adhering to the dinucleotide probabilites.

    Args:
        sequence: input sequence.
        number_random_seq: Number of randomised sequences returned.

    Returns:
        number_random_seq x randomised sequences of equal length to the input
        sequence in a list.

    Raises:
        ValueError: input_string contains characters other than ATGC.
    """
    pass


def make_markov_matrix(input_sequence: str) -> np.matrix:
    """
    Returns markov matrix based on the input sequence,

          A      T      G      C
        A P(AA)  P(AT)  P(AG)  P(AC)
        T P(TA)  P(TT)  P(TG)  P(TC)
        G P(GA)  P(GT)  P(GG)  P(GC)
        C P(CA)  P(CT)  P(CG)  P(CC)

        where P(AA) is the probability of A following an A.

    Args:
        input_sequence: Input sequence.

    Returns:
        Markov matrix as 4x4 np.matrix with propabilities of nucleotide pairs.

    Raises:
        ValueError: input_string contains characters other than ATGC.
    """
    pass

def create_random_sequence(input_sequence: str,
    markov_matrix: np.matrix, number_random_seq: int = 1) -> list:
    """
    Returns a list with number_random_seq randomized strings, each with length
        of the input string, and based on the probabilities from
        the markov_matrix.

    Args:
        input_sequence: Input sequence.
        markov_matrix: Probability matrix.
        number_random_seq: Number of randomised sequences returned.

    Returns:
        List of randomised sequences with number_random_seq entries.
    """
    pass

"""
Comments:
* What about non ATGC letters in the input sequence? Should the matrix be 
dynamically generated, matching other letters in the input sequence?
"""
```

**Comment by mzavolan** [comment]
Perfect idea to split the functionality in the two parts that you identified! However, the input will be a set of sequences, not just one, and the matrix should be constructed from all (looping though all input sequences). The issue of non-ACGT characters is a good one, because we do get ambiguous base calls in these files. Rather than quitting the program though, I would handle these characters more smoothly. You could include an option to the program to specify whether such characters should be ignored or considered, or, even more specifically, you can provide a default alphabet and allow the user to overwrite it or extend it. Seems that you also exposed plenty of interesting tests! The docstring is good.

**Comment by uniqueg** [comment]
Closing this for now as we chose to implement a brute force algorithm for 3' adapter extraction for the meantime.
