### ISSUE TITLE
Publish HTSinfer on Bioconda

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/htsinfer#145]
Being available on HTSinfer would make the tool easier to consume/install by users. Moreover, ZARP-cli currently cannot run the _ZARP_ HTSinfer pipeline in Conda mode, because HTSinfer isn't available on Conda.

**Comment by balajtimate** [comment]
HTSinfer is now available on Bioconda: https://anaconda.org/bioconda/htsinfer, as well as on the biocontainers Docker hub: https://quay.io/repository/biocontainers/htsinfer. 
When we create a new release version, it'll be automatically updated. 

We can also update ZARP-cli now to run it in Conda mode.
