### ISSUE TITLE
Compute histograms of inter-motif distances

### ISSUE THREAD

**Issue by mzavolan** [zavolanlab/htsinfer#15]
Given a set of motifs and a set of sequences, compute histograms of inter-motif distances for all pairs of motifs and return pairs for which there is a significantly preferred distance. That is, loop across all sequences and record the distance between that start positions of the two motifs in every sequence. Note the symmetry, namely that distances between motif1 and motif2 will be the negatives of distances between motif2 and motif1. To not deal get twice the same underlying configuration, we can keep track only of non-negative distances. If there really is a preferred distance, this distance should occur more often than all others. We will have to decide on a cutoff. Here we could use the statistics we compute for generating the randomized sequences to calculate how often we expect specific motifs at specific distances. But maybe a simpler rule of thumb would work well enough, e.g. for each motif, the most frequent distance, as long as it's x fold higher than the average or than the second most common distance.

**Comment by maritvanderdoes** [comment]
I would like to work on this project together with Camila Pulido

**Comment by uniqueg** [comment]
Thanks @maritvanderdoes!

@dcpb0: Hi Camila, as long as you don't leave a comment in the issue, I can't assign you. A thumbs up is apparently not enough.

**Comment by dcpb0** [comment]
@uniqueg Hi Alex, thanks for letting us know. I would like to work on this issue with Marit van der Does.

**Comment by maritvanderdoes** [comment]
Hello. We have finished the code, and uploaded it to the master branch in the copied repository on camila's github (dcpb0). Then we created the pull request. However, we are not sure if it worked out.  Please let us know when its not working.

**Comment by uniqueg** [comment]
Closing this for now as we chose to implement a brute force algorithm for 3' adapter extraction for the meantime.
