### ISSUE TITLE
Compare inferred read length statistics to SRA metadata

### ISSUE THREAD

**Issue by balajtimate** [zavolanlab/htsinfer#151]
I've been looking into the reported read length data from the SRA sample dataset, reran the ones with errors and modified the testing script so the inferred length would always get reported, no Undecided left (please compare it to the results in [the performance issue](https://github.com/zavolanlab/htsinfer/issues/109#issuecomment-1801481936))
<img src="https://github.com/zavolanlab/htsinfer/assets/51365402/46cc68d8-ec1b-40d5-9e97-be06732ecb0b" width="400">

With this, there were 563 matches and 215 mismatches left. 
Then I found that the read statistics from the second mate in paired samples didn't get correctly reported in the results, so I fixed that (see commit). I also added the additional read statistics (mean, median, mode) to the results, and compared the SRA reported read length to that, after which most (745 out of 779) read length results were matches.  
<img src="https://github.com/zavolanlab/htsinfer/assets/51365402/5bca4b3b-ef25-425e-9d4a-394ee8677e52" width="400">
I checked the rest individually (33 + 1 sample where there was no length metadata) on SRA, all of those had the mean read length reported in our sample data, and the difference was always ±1 (e.g. [SRR18675578](https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&acc=SRR18675578&display=metadata) with the SRA reported mean length of 138, in our sample data table we had 137 bp, while the inferred mean is 138.03, so I corrected that). 

I would say the read inference works as intended now, with the additional stats getting reported, it matches the metadata from SRA.

**Comment by uniqueg** [comment]
That's fantastic work, thanks a lot @balajtimate :pray:
