### ISSUE TITLE
feat: only map when lib source is given, argument to force mapping otherwise

### ISSUE THREAD

**Issue by balajtimate** [zavolanlab/htsinfer#153]
**Is your feature request related to a problem? Please describe.**
Currently, when inferring the orientation of the reads, the sample reads are mapped against the whole (unfiltered) transcripts library, when the library source is either not inferred or not given as input. This alters the result of the orientation inference. 

**Describe the solution you'd like**
The program should check whether the library source is inferred or given, and only subset the transcripts and map to those based on the source organism. Also implement a CLI argument to force the mapping, even when those conditions are not met (but also make it known that the results are based on all the transcripts and no filtering was done). 

**Additional context**
Should the same apply when inferring the library layout relationship by mapping? As in only map when lib source is known.

**Comment by uniqueg** [comment]
I think that at least initially we should only use mappings if the library source could be inferred. I'm afraid the behavior when mapping against _all_ sources is just too unpredictable.
