### ISSUE TITLE
Create dataset overview tables

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/htsinfer#154]
Create spreadsheet of different datasets used for the analysis.
Different tabs for different datasets (e.g., SRA, Zavolab, Meric).

It's important that all libraries we report on are published.

**Comment by balajtimate** [comment]
Here is the spreadsheet with the datasets, on different tabs:
[htsinfer_test_datasets.xlsx](https://github.com/zavolanlab/htsinfer/files/14010216/htsinfer_test_datasets.xlsx)
