### ISSUE TITLE
Create overview figure panel

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/htsinfer#155]
Create high level ("graphical abstract") overview of what HTSinfer does, in vector graphics.

**Comment by balajtimate** [comment]
![htsinfer_workflow_overview](https://github.com/zavolanlab/htsinfer/assets/51365402/7246ad8d-e6ee-426c-b0fc-ccbf58718e42)
Would something like this work?

**Comment by uniqueg** [comment]
This is great - thanks a lot @balajtimate!

The only thing I'm not sure about is the tool names in the blue boxes. What do they signify? Do we use `kallisto` to "infer" the library source, STAR for the read orientation and Cutadapt for the 3' adapter sequences?

**Comment by uniqueg** [comment]
And perhaps about the pictograms:
- The library type isn't very obvious. Might be better to have something that indicates single vs paired. Not sure what though.
- For the 3' adapter sequence, I think that having two lines, at first glance, suggests a double strand (even though it's not) - so perhaps increase the letter sice a bit and then use only one row?

**Comment by balajtimate** [comment]
> Do we use `kallisto` to "infer" the library source, STAR for the read orientation and Cutadapt for the 3' adapter sequences?

Yeah, exactly. Technically, STAR is also used for library _type_ inference when the seq_ids are not present, but for the read orientation it's always used, so for the overview I think it's enough to put it there. 
If the flow is not obvious, I could put some arrows to indicate it more visibly.
> The library type isn't very obvious. Might be better to have something that indicates single vs paired. Not sure what though.

Yeah 😅 Maybe a single and double arrows from the read orientation pictogram, and for that, add another pair of arrows showing the forward read as 2, and reverse as 1?
> so perhaps increase the letter sice a bit and then use only one row?

Sure, I'll  change that.

**Comment by uniqueg** [comment]
Yes, good idea about the library type pictogram.

I would probably put STAR in as well for the type inference, but maybe with a slightly in a lighter blue shade or with a pair of brackets around it? Just for completion.

Also, how is Cutadapt used for the 3' adapter sequence? I thought Rohan implemented some fancy search algorithm for that. Sure Cutadapt isn't just used for polyA tails?

**Comment by balajtimate** [comment]
Here is an updated version:
![htsinfer_workflow_overview](https://github.com/zavolanlab/htsinfer/assets/51365402/c60d9ee1-0812-4d06-90c0-f75dfd405f32)

**Comment by uniqueg** [comment]
Great! I think you can just attach the SVG file as well here, then close the issue :)

**Comment by balajtimate** [comment]
Here is the SVG:
![htsinfer_overview_figure](https://github.com/zavolanlab/htsinfer/assets/51365402/359e639e-94fd-4e71-a914-372aca53821c)
