### ISSUE TITLE
Align motifs

### ISSUE THREAD

**Issue by mzavolan** [zavolanlab/htsinfer#16]
Given a set of motif pairs with specified inter-motif distances, align them and generate clusters of motifs. Motif pairs that occur in reads at a preferred distance would be defined in a regular expression-like manner as [M1]+[N]*[M2]+, where [M1]+ indicates the bases of motif 1, [M2]+ indicates the bases of motif 2, and [N]* indicates that there can be spacers of unknown sequence in between. We will align these motifs using a greedy approach, calculating the similarity of motifs in each pair and aligning those with highest similarity. Since we are looking for well-defined sequences (no ambiguity of bases at any position), we can be very strict, aligning only motifs which are compatible with each other (no mismatches). To calculate the similarity, we slide one motif over the other and record the number of matching bases. 'N's do not count. Once two motifs are aligned, they generate a new motif, which is the consensus of the two, with 'N's in one motif being resolved by bases at the corresponding positions in the other motif. All distinct consensus motifs at the end of this clustering procedure should be reported.

Example: let's say we have the following motifs as input ['ACANNNTGT', 'CACNNNGTG', 'CANNNGT', 'GGANGGA', 'GGCNNGA'] along with a threshold a minim score).
At each step, we have to calculate the similarity (score) for all motif pairs. Taking the first two, we would start sliding one motif over the other, calculating the number of matching bases:
ACANNNTGT
                    CACNNNGTG
------------------------- matches = 0

ACANNNTGT
                  CACNNNGTG
------------------------ matches = 0
...
ACANNNTGT
  CACNNNGTG
------------------------ matches = 5 (Note: I counted C-N and T-N each as a half match)
...
  ACANNNTGT
CACNNNGTG
------------------------ matches = 5 (similar to the one above)
etc.
Based on the above alignments, the best score for the two motifs would be 5, with 2 alternative alignments. 

We would similarly calculate all pairwise scores, and then merge the two motifs with the highest scores into one. In the case of ties, we could chose randomly among the possibilities. Other choices are possible, so this can be implemented as an option. Assuming that we take the following alignment
ACANNNTGT
  CACNNNGTG
The merged motif will look like this: ACACNNTGTG, where some of the N's in the original motifs became constrained by the alignment. After the merge, the motif list will be shorter by one. We keep going, always picking the two motifs with highest score and merging them, until the list consists of a single motif, or until the score of any two motifs drops below the threshold that we have as input parameter. We then return the list of remaining motifs.

**Comment by vildekveim** [comment]
I would like to work on this project with Nathalie Immerzeel

**Comment by Nimmerzeel** [comment]
That's me! Just to repeat: I would like to work on this project with Vilde Kveim.

**Comment by mzavolan** [comment]
Thanks, you're assigned!

**Comment by uniqueg** [comment]
Thanks guys, @mzavolan assigned you

**Comment by uniqueg** [comment]
No PR was filed and it does not look like any code was added to any of the two forks.

**Comment by uniqueg** [comment]
Closing this for now as we chose to implement a brute force algorithm for 3' adapter extraction for the meantime.
