### ISSUE TITLE
Extend motifs based on nucleotide representation in sequenced reads

### ISSUE THREAD

**Issue by mzavolan** [zavolanlab/htsinfer#17]
Given a set of core motifs, check whether they represent parts of longer motifs in sequenced reads. Extend left and right if the nucleotide composition in these positions is very biased. That is, starting from all occurrences of a core motif in the reads, determine the frequencies of A,C,G,T at the left- and right-flanking positions, and calculate the entropy of this distribution. Ideally, the motif can be extended if the flanking positions contain one specific nucleotide, i.e. entropy is 0. But sequencing errors could introduce some noise. So it may be necessary to introduce a cutoff. Continue the extension greedily until the entropy becomes too high.

**Comment by stinea98** [comment]
If possible, I would like to work on this issue as part of the individual project!

**Comment by mzavolan** [comment]
It's fine, in principle, but let's make a plan for the whole independent project then.

**Comment by stinea98** [comment]
**This would be my proposal:**

**Input:** list of core motifs & list of reads
**Output:** list of extended motifs

1) find core motif in every read (record start and end position)
2) determine the frequencies of nucleotides at the left- and right-flanking positions, compute the percentage of each nucleotide at the positions
and the calculate the entropy at each position
—> is the following formula for entropy correct? entropy = - sum(P(i)*log10(P(i)) over all nucleotides(i)
3) if entropy>cutoff: extend motif in the right/left flanking position 
4) continue until entropy<cutoff for both right and left flanking position

I don’t understand the following sentence: “Continue the extension greedily until the entropy becomes too high”
What does “greedily” mean? And isn’t there a max entropy?

**Comment by mzavolan** [comment]
The proposal is almost on the mark. The formula for the entropy is correct (base of the logarithm is usually 2 though, to express the entropy in bits). However, we will be extending if the entropy is **less** than some cutoff value, because we are looking for exact nucleotide matches. That means, if we have one specific flanking nucleotide flaking the core motif, the entropy will be 0 and will extend the core motif. By 'greedily' I mean that once the entropy is above the threshold we stop, we do not check positions further away from the core motif match.

**Comment by stinea98** [comment]
ok great, thanks for the clarifications! 👍

**Comment by uniqueg** [comment]
Closing this for now as we chose to implement a brute force algorithm for 3' adapter extraction for the meantime.
