### ISSUE TITLE
Construct position-dependent frequency profiles

### ISSUE THREAD

**Issue by mzavolan** [zavolanlab/htsinfer#18]
Given a set of motifs and a set of sequences, construct a position-dependent frequency profile of occurrence of the motifs within reads. This can be done by scanning all the reads with a particular motif, looking for perfectly compatible matches. That is, if the motif occurs internally in the read, it should be found precisely, and if the motif occurs at the 3' or 5' end of the reads it should be matched perfectly over the bases that are present. Record all the positions in the reads where the motif occurs and construct a histogram. If the motif occurs more than once in a read, count it fractionally towards each of those positions (e.g. if the motif occurs at 2 positions, each of these positions gets a count of 1/2). The simple implementation of this procedure will be slow (nr motifs * nr reads * read length), so make use of multiprocessing to speed things up.

**Comment by mariapau189** [comment]
Hello, I would like to work on this issue

**Comment by uniqueg** [comment]
Thanks @mariapau189, assigning you

**Comment by mariapau189** [comment]
Hi! This is what I have so far, I still have to implement reading the different motifs from a file...and then the histogram. My idea is to print each sequence ID along with the positions where the motif is found. Each motif would output one position file. Then I would calculate the frequency of each position. 

The following is printing only the the sequence IDs, without the positions, and I'm stuck here. I'm using the SRR11971558_2.fastq file to test, and there are 3 "ATA" in the second record. 

#!/usr/bin/env python
    
import re
from Bio import SeqIO   
import sys

sys.stdout=open("output_positions.txt","w")

def reader ():
    motif = ("ATA") #This should also be read from a file
    for record in SeqIO.parse("SRR_558.fastq", "fasta") :
        print (record.id)
        sequence = str(record.seq)
        s = re.finditer(motif,sequence)

        for match in s:
            print (match.start())

sys.stdout.close()

**Comment by uniqueg** [comment]
Closing this for now as we chose to implement a brute force algorithm for 3' adapter extraction for the meantime.
