### ISSUE TITLE
Count occurrences of adaptors/contaminants

### ISSUE THREAD

**Issue by mzavolan** [zavolanlab/htsinfer#19]
Given a set of known adaptors/contaminants and an input fastq file, count the number of matches to potential adaptors/contaminants. Similar to issue #19, but instead of making position-dependent profiles, the number of matches and proportion of matched reads should be determined. Thus, the same inner function can be used for both to identify motif matches within a read. Then the number of motifs per read can be tabulated, where partial occurrences would be counted with a weight which is the fraction of the motif that was matched to the read.

**Comment by HiyanZhang** [comment]
I would like to work in this issue if it is possible.

**Comment by uniqueg** [comment]
Thanks @HiyanZhang, assigned you

**Comment by HiyanZhang** [comment]
For this issue, it wrote "Given a set of known adaptors/contaminants and an input fastq file, count the number of matches to potential adaptors/contaminants." May I ask how/where should I get those set of  known adaptors/contaminants?
Thanks!

**Comment by mzavolan** [comment]
They will be inferred with code resulting from the implementation of other issues in the project.

**Comment by HiyanZhang** [comment]
Got it, thanks a lot.

**Comment by uniqueg** [comment]
Closing this for now as we chose to implement a brute force algorithm for 3' adapter extraction for the meantime.
