### ISSUE TITLE
Identify potential 'spacer' k-mers 

### ISSUE THREAD

**Issue by mzavolan** [zavolanlab/htsinfer#20]
Given a set of reads, identify k-mers with very high occurrence at a specific position in the reads. 'Spacer' k-mers should occur in most sequences with a highly peaked position-dependent frequency. We could identify these cases by fitting a mixture of two uniform distributions to the positions of the motif in reads, expecting that one component of the mixture will have much narrower range than the other and a much higher weight in the mixture. A package that could be used for the fitting is pomegranate (https://pomegranate.readthedocs.io/).

**Comment by Anunnaki1000** [comment]
Hi, I would like to work on this issue

**Comment by mzavolan** [comment]
Great, go ahead!

**Comment by uniqueg** [comment]
Unassigned. See https://github.com/zavolanlab/htsinfer/pull/46

**Comment by uniqueg** [comment]
Closing this for now as we chose to implement a brute force algorithm for 3' adapter extraction for the meantime.
