### ISSUE TITLE
Identify potential barcode k-mers

### ISSUE THREAD

**Issue by mzavolan** [zavolanlab/htsinfer#21]
Barcodes should consist of a small set of k-mers with the same length and a very similar position-dependent frequency of occurrence within reads. From the motif enrichment function we will get a list of strings that are considered significantly enriched among the reads. Another function will also implement computing the position-dependent frequency of occurrence of a k-mer in a set of input reads. We will use these two pieces of information, as well as the reads themselves to identify a set of motifs of the same length that together are represented across a minimal fraction of the reads and therefore could represent library barcodes. Inputs:  set of motifs (of potentially different lengths), set of reads. The function will first construct position-dependent frequency distributions. These will be compared pairwise across motifs of the same length. The list of pairwise distances will be traversed from smallest to largest, until a maximum threshold is reached, building sets of k-mers of the same length and with similar position-dependent frequencies. The coverage of reads by each set will be determined. The k for which the coverage satisfies a min threshold is selected. If multiple k's satisfy the condition, the largest one is chosen.

**Comment by ClkElf** [comment]
Hello, I would like to work on this issue, if it is possible.
Best,
Elifnaz Celik

**Comment by mzavolan** [comment]
Thanks, go ahead!

**Comment by buffalo0124** [comment]
Hello, I would like to work on this issue with Elifnaz
Ji Hoon

**Comment by mzavolan** [comment]
Go ahead, and please try to talk with each other.

**Comment by ClkElf** [comment]
It is okay with me, we can work together!

**Comment by uniqueg** [comment]
Closing this for now as we chose to implement a brute force algorithm for 3' adapter extraction for the meantime.
