### ISSUE TITLE
Extract RP transcripts for provided organism

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/htsinfer#25]
The repository contains a file with transcript sequences of highly expressed ribosomal proteins for hundreds of organisms (prepared for the purpose of inferring the organism from the data, a functionality which has not yet been merged). You can find it at  [`data/transcripts.fasta`](https://github.com/zavolanlab/htsinfer/blob/dev/data/transcripts.fasta). In order to map the reads against the transcriptome in #26 and #27 of the read orientation inference process. we will need to select from this file only the FASTA entries of those transcripts that originate from the organism that was provided through #23 & #24.

To do so, implement a function that parses the identifier lines of [`data/transcripts.fasta`](https://github.com/zavolanlab/htsinfer/blob/dev/data/transcripts.fasta) and selects those entries (identifier and corresponding sequence) that match the 4th field if the provided organism is a string (organism short name) _or_ the 5th column if the provided organism is an integer (taxon ID). See #24 for more info on this. Write the resulting records to a file in the temporary directory created in #33 and return the path to the resulting transcripts file. Make sure you call your new function in the main function `infer()` in the [`htsinfer/infer_read_orientation.py`](https://github.com/zavolanlab/htsinfer/blob/dev/htsinfer/infer_read_orientation.py) module and assign the result to a variable that can be used subsequently to create an index of the file (#26).

**Comment by rockdeme** [comment]
Hey, I'd like to work on this with Daniel Batora.

**Comment by danielbatora** [comment]
Hey, I'd like to take this issue.

**Comment by uniqueg** [comment]
Sure, @rockdeme & @danielbatora

**Comment by danielbatora** [comment]
This is the code that generated the error : 

```python
from Bio import SeqIO

reads = []
with open("transcripts.fasta", "rU") as handle:
    for record in SeqIO.parse(handle, "fasta"):
        reads.append(record.description.split("|")[3])
```

**Comment by uniqueg** [comment]
@danielbatora: unfortunately I couldn't reproduce the error. However, the file obviously has some issues. Most of the times it has Unix-style line breaks, but sometimes Windows-style line breaks. And there's a really weird block of characters (looks like binary content) starting in line 166572. I have to get back to the person who created this file, but for now I have removed the "binary" characters and changed all line breaks to Unix style. As I couldn't reproduce the error, I can't verify that the new version of the file is okay. Let's try this together tomorrow.

**Comment by danielbatora** [comment]
@uniqueg I pushed the pilot function to the fork repo. As of now, the function accepts SeqRecord objects, so it does not run into error with the corrupted file. When reading and cleaning the file happened inside the function (in that case the function acceps a path to the FASTA file as an argument, the error did not let the function to return. Other than that, which file type should I use when creating the temporary directory ? Is pickle good?

**Comment by uniqueg** [comment]
Thanks @danielbatora: can you try with the updated file? I think it's best if the function takes and returns a FASTA file path, otherwise we would need an extra function to read it and just outsource the problem :)

**Comment by danielbatora** [comment]
@uniqueg Okay, should the output file be a FASTA as well, or pickle ?

**Comment by uniqueg** [comment]
Yup, FASTA. The STAR alignment program used in #26 and #27 is not a Python package and thus cannot deal with a SeqRecord object or a Pickle file.

**Comment by danielbatora** [comment]
Okay, Done ! Should the temporary directory created in another issue be an argument of this function ? I do not understand it completely.

**Comment by uniqueg** [comment]
Yes, good point, the temporary directory needs to be passed as an argument (e.g., `tmp_dir`). I will implement the code to create the temp directory, you can add the parameter to the function signature (remember to add a type hint and a description in the docstring) and then create your output file as something like:

```python
import os

out_file = os.path.join(tmp_dir, "transcripts_filtered.fasta")
```

(untested)

**Comment by uniqueg** [comment]
As discussed in the chat:

```python
if (
    isinstance(organism, str) and 
    record.description.split("|")[3] == organism
):
    data.update({organism + "_" + str(counter) : str(record.seq)})
    counter += 1 
elif (
    isinstance(organism, int) and
    record.description.split("|")[4] == str(organism)
):
    data.update({str(organism) + "_" + str(counter) : str(record.seq)})
    counter += 1 
```

When merging all conditions into a single `if` this would become something like:

```python
if (
    # check for organism short name
    (
        isinstance(organism, str) and 
        record.description.split("|")[3] == organism
    ) or
    # check for taxon identifier
    (
        isinstance(organism, int) and
        record.description.split("|")[4] == str(organism)
    )
):
    data.update({str(organism) + "_" + str(counter) : str(record.seq)})
    counter += 1 
```

Note that this last solution, while having a relatively hard to read conditional section (which is why I added comments), avoids code duplication, which is always a source of error (note that the `data.update({str(organism) + "_" + str(counter) : str(record.seq)})` call with the extra `str()` should work for both `int` and `str` organism arguments)

**Comment by uniqueg** [comment]
Hi @danielbatora & @rockdeme , actually forgot to insist on unit tests for the function. But seeing that the file `tests/test_infer_read_orientation.py` where these tests should go is still empty and that it's rather hard to start on an empty file, and there are currently only unit tests for the wrapper function `infer()` in `tests/test_infer_single_paired.py` either, but not tests for each individual function, as examples, I think I can take care of this for this PR. Benefit of the first PR ;-)

That is, unless you would like to try it yourself. In that case, please let me know. In general, if you make changes to your feature branch and push them, the PR will be updated automatically, so it's easy to add tests (or any other changes) to the existing PR.

**Comment by danielbatora** [comment]
Hi @uniqueg , are we having one more hackaton lecture? In that case, we could do the unit tests or start a new issue (if there is any that noone is assigned to ). What do you suggest ?

**Comment by uniqueg** [comment]
Yes, we will have one more, so feel free to do it then. I will see that I'll add some more examples for the `htsinfer/infer_single_paired.py` module until then. I'd prefer to keep the code and corresponding tests in one PR
