### ISSUE TITLE
Prepare transcript index for mapping

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/htsinfer#26]
In order to efficiently map reads to reference sequences, mapping programs require an index of the reference sequences (here: transcripts of genes coding for highly expressed ribosomal proteins, see #25 for more details).

Write a function that prepares an index of the subset of transcripts prepared in #25 with the [`STAR`](https://github.com/alexdobin/STAR) program. Accept the path to the transcripts file as an input and return the path to the built index. Use a [subprocess](https://docs.python.org/3/library/subprocess.html) to call the index generation. Write the resulting index to a directory path in the temporary directory created in #33. Make sure you have installed `STAR v2.7.6a` first (via Conda) and add it to the `environment.yml` file (if it is not already present from #27). Insert a call to your new function in the main function `infer()` in the [`htsinfer/infer_read_orientation.py`](https://github.com/zavolanlab/htsinfer/blob/dev/htsinfer/infer_read_orientation.py) module. Assign the result (i.e., the index directory path) to a variable that can be used subsequently to map the reads (#27).

**Comment by S1moFara** [comment]
Hi, I'd like to take this issue.

**Comment by uniqueg** [comment]
@S1moFara thanks, assigning you

**Comment by uniqueg** [comment]
Currently being implemented in #73. Closing for better overview.
