### ISSUE TITLE
Map reads to RP transcripts

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/htsinfer#27]
Alignments to transcripts will relatively easily tell us the orientation in which RNA sequence fragments are read in a given library. Here, we will use the transcriptome index generated in #26 to map the reads selected from #11.

Write a function to implement the mapping. Use a [subprocess](https://docs.python.org/3/library/subprocess.html) to compute alignments with  [`STAR`](https://github.com/alexdobin/STAR). For the results directory, provide a path in the in the temporary directory created in #33. Return the path to the results directory to the calling function. Make sure you have installed `STAR v2.7.6a` first (via Conda) and add it to the `environment.yml` file (if it is not already present from #26). Insert a call to your new function in the main function `infer()` in the [`htsinfer/infer_read_orientation.py`](https://github.com/zavolanlab/htsinfer/blob/dev/htsinfer/infer_read_orientation.py) module. Assign the result (i.e., the results directory) to a variable that can be used subsequently.

**Comment by nevilJg** [comment]
Hi there let me try this one, I think I will need some help and time (because I am currently also doing Blockkurse) but im happy to learn new things.
~Nevil

**Comment by uniqueg** [comment]
Sure, thanks - assigned you. You can discuss with @S1moFara who is taking care of #26, which will be almost exactly the same (almost same code, but a different call to STAR).

**Comment by uniqueg** [comment]
Currently being implemented in #73. Closing for better overview.
