### ISSUE TITLE
Extract alignment configuration

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/htsinfer#28]
Mappers will align reads either in sense or antisense (i.e., reverse complement) configuration. The standard format for reporting read alignemnts, in human-readable form, is the [SAM format](https://samtools.github.io/hts-specs/SAMv1.pdf). Whether a read was mapped either to the sense or antisense strand of the template is visible from the FLAG field (see SAM specification, section 1.4), which is a combination of bitwise flags, expressed as a decimal integer. In particular, the `0x10` bit tells us whether a given read was reverse-complemented for alignment.

Write a function that takes as an input a path to a BAM file and returns a tuple of two items representing the counts of
alignemnts in that file, where the `0x10` bit is (1) unset and (2) set, i.e., where the read could be aligned in its given or reverse-complemented configuration, respectively. Note that due to the very large file sizes of typical alignment files, SAM files are typically compressed, and will be available in either BAM or CRAM format. They can be parsed with the Python package [`pysam`](https://pysam.readthedocs.io/en/latest/api.html). Insert a call to your new function, taking the path of the pseudobam file created in #27 as its argument, into the main function `infer()` in the [`htsinfer/infer_read_orientation.py`](https://github.com/zavolanlab/htsinfer/blob/dev/htsinfer/infer_read_orientation.py) module. Assign the result (i.e., the results directory) to a variable that can be used subsequently.

**Comment by hossal** [comment]
I would like to solve this issue (Salome Hosch)

**Comment by mzavolan** [comment]
Go ahead!

**Comment by uniqueg** [comment]
Currently being implemented in #73. Closing for better overview.
