### ISSUE TITLE
Create temporary directory

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/htsinfer#33]
Several functions that need to be added to implement the read orientation inference functionality will need to write temporary data to the disk. In order to keep things organized and allow cleaning up temporary data after we are done with the inference, a temporary directory should be created to keep all of the data that is written in subsequent steps.

Implement a function that accepts a directory path, creates a temporary directory in that directory and return the path to the temporary directory. Make sure you call your new function in the main function `infer()` in the `htsinfer/infer_read_orientation.py` module and assign the result to a variable that can be used subsequently (#25, #26, #27, #34). Also make sure to write at the very end of the `infer()` function the code required to delete the temporary directory! All other required calls/code to implement the read orientation inference functionality will go _between_ the creation and deletion of the temporary directory.

**Comment by yeastethanol** [comment]
Hi. I would like to work on this issue.

**Comment by uniqueg** [comment]
Sure, thanks @yeastethanol

**Comment by yeastethanol** [comment]
Hi @uniqueg, can you please check if my code works?
Here is the link: https://github.com/yeastethanol/htsinfer/blob/issue33_modifiy/htsinfer/infer_read_orientation.py

**Comment by uniqueg** [comment]
@yeastethanol Sorry for the late reply. It looks quite alright, but there are a few comments I have. It's easier to do that if there's an open PR (because I can comment any given line), so please open one and I'll get back to you.
