### ISSUE TITLE
Find motif matches within a read

### ISSUE THREAD

**Issue by mzavolan** [zavolanlab/htsinfer#35]
For constructing the position-dependent profile of motif occurrences and counting the reads that match individual motifs (issues #18 and #19), we need a functionality of finding where a specific motif occurs within a read. We could do this by sliding the motif from left to right, starting from a minimum overlap between motif end and read start and ending at some minimum overlap between motif start and read end, reporting all of the consistent matches as a list of tuples, (position:fraction of motif matched). Running this function over all reads and all motifs will be time-consuming, so minimize the number of tests that are done to decide whether the motif matches or not.

**Comment by ymoon06** [comment]
I would like to work with this issue

**Comment by uniqueg** [comment]
Thanks @ymoon06, assigned you

**Comment by Dhryata** [comment]
I would like to join in on this issue

**Comment by mzavolan** [comment]
OK, assigned, please talk to each other

**Comment by ymoon06** [comment]
Dear Dhryata, can you send me whatsapp number again? By the time you gave number to me, the host finished the zoom, so I couldnt see your number properly. I tried several things but it seems not the case. Sorry about this.

**Comment by Dhryata** [comment]
Hi! @ymoon06 it is +91 9619303703. See you in class :)
