### ISSUE TITLE
Modify Final Output

### ISSUE THREAD

**Issue by rohank63** [zavolanlab/htsinfer#65]
For now, We are keeping the ouput as strings for infer_organism and infer_adapter just like infer_single_paired:
### infer_organism.py
> Output: organism name, NA, invalid_file

### infer_adapter.py
> Output: adapter sequence, NA, invalid_file, not_available
 
We can later make use of Pydantic package to change the final output, once the other functionalities are done.

**Comment by uniqueg** [comment]
Closing as this is already being implemented like that.
