### ISSUE TITLE
Handle multimappers correctly

### ISSUE THREAD

**Issue by rohank63** [zavolanlab/htsinfer#67]
A given read can map to multiple locations. It is important, however, that every read is counted only once. Also, the resulting alignments may sometimes be to the sense and other times to the antisense strand.
So to make sure these constraints are considered, it is necessary to collapse the outcomes of all the alignments of a given read into one outcome. Say, read 12345 aligns to 5 different locations in the RP transcripts. If all of the alignments do not require taking the reverse complement of the read (i.e., they are on the sense strand), you should count 1 towards "forward", not 5. If all of the alignments need to be reverser complemented, then you should count 1 towards "reverse", not 5. Now, if some of the alignments are "forward" and some of them are "reverse", I think it's best if you omit that read from the counting altogether, because the origin of that particular read cannot be safely established and thus the orientiation information from that read will also be insecure. Alternatively (especially if we don't get many reads aligning to the RP transcripts), you could assing fractions of counts to "forward" and "reverse": e.g., you had 4 alignments consistent with "foward" and 1 with "reverse", you could count 0.8 for "forward" and 0.2 for "reverse".

**Comment by uniqueg** [comment]
Implement with or after #73.
