### ISSUE TITLE
Infer library type if sequence identifiers do not contain mate info

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/htsinfer#85]
**Is your feature request related to a problem? Please describe.**

When depositing FASTQ files to the [Sequence Read Archive (SRA)](https://www.ncbi.nlm.nih.gov/sra), the original sequence identifiers are not preserved. In the sequence identifiers generated by the SRA, mate information is not retained. Therefore, the current regex-based inference of the library type (single vs paired) does not work for FASTQ samples derived from the SRA.

As using HTSinfer on libraries obtained from SRA is an important use case, this is a critical problem.

**Describe the solution you'd like**

Whether two different libraries are mates of one another can also be inferred indirectly, based on two assumptions:
1. Mates have the same sequence identifiers
2. Mates of a paired-ended library generally (though possibly not always) map to the same transcripts. Also, the alignment orientation of each mate should match the ones expected based on the read orientation.

So, for libraries whose type cannot be inferred based on the regex approach (faster!), mate library files could be individually mapped to the set of transcripts (or mappings used from another step) and the alignments could be analyzed for the fraction of mate pairs (reads with same identifier) that map to the same transcript.

**Describe alternatives you've considered**

Alternatively, one could possibly use a mapping strategy where both mate library files are supplied.

**Comment by BorisYourich** [comment]
Currently, the program is implemented in such a way, that the library_type information is necessary in the get_read_orientation step. I could implement a mapping step in the get_library_type, but then we would be mapping the libraries twice if the sequence identifiers aren't enough for inferring whether the files are mates. 

One Idea would be to run the paired-end mapping with STAR if the seq_ids are insufficient and if the files are actually mates then add a flag to the config that would tell the get_read_orientation step that the mapping has already been performed and where it can find the results.

Does that sound like a reasonable solution or is there any better idea?

**Comment by uniqueg** [comment]
Thanks a lot @BorisYourich. Yeah, some neat/clean way of avoiding double mapping would be great.

However, these could also be two separate PRs in a more agile way. The first would be focusing on _this_ issue only, independent of the fact that this may mean double mapping. Then in the second, a mechanism would be introduced to access mappings from elsewhere if already available.

Perhaps the two PR approach might be better, as each individual PR would be smaller and easier to write, test and review. It might also allow us to focus on a more generic way of passing available intermediate results between inference functions. To do this neatly is not necessarily trivial, especially if done generically. But it could greatly help avoid circular dependencies and wasted resources if/when HTSinfer becomes more complex with time.

**Comment by BorisYourich** [comment]
Okay, I will start working on the variant that uses double mapping, then later clean it up by possibly adding a Mapping class that takes care of STAR and it's outputs or something along those lines as we will see fit.

**Comment by uniqueg** [comment]
Perfect :) Thanks a lot!

**Comment by BorisYourich** [comment]
I am currently at a point where I map the reads and parse the STAR mapping stats, although I am not sure how should I continue. Should I introduce another user configurable parameter that will decide what fraction of (mapped reads / input reads) is still considered a split_mate library or keep it at a default, say more than a half?

**Comment by uniqueg** [comment]
Thanks @BorisYourich. I think it should indeed be a configurable parameter. Or multiple.

What I think may be more relevant than $n_{mapped}/n_{input}$ would be to map both mates separately and checking the fraction of mates that can be mapped to compatible loci. Given that orphaned/"singleton" reads/mates are generally very rare, this should be a very high fraction (I would put a default cutoff of, say, >0.95).

I would also put a cutoff on the minimum absolute number of mates that map to compatible loci. And that I would put at, I dunno, maybe 100?

Note that for that approach, parsing the mapping stats is not enough. You need to parse the individual alignment files to determine mates (that is, reads with the same IDs from different libraries) that are compatible or not ("concordant pairs").

Concordant pairs would come from the same fragment and therefore:
1. Map to same transcript (unless they are from chimeric transcripts; rare!)
2. Map at a compatible distance
3. Map with the expected orientation

As we don't know 3. I would ignore that. Also, as we don't know the fragment length distribution (which informs 2.), I would set maybe a configurable max distance of 1'000 - which would have a Z score of ~4 even for a library with rather large fragments of 400 nts and variability (+/- 150 nts).

Does that make sense to you?

**Comment by BorisYourich** [comment]
Yes sure I understand, I was not sure that it is necessary to map the mates separately, but not knowing the library orientation it makes sense, I will rework it.
