### ISSUE TITLE
Infer presence of polyA tails in reads

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/htsinfer#86]
**Is your feature request related to a problem? Please describe.**
TBA

**Describe the solution you'd like**
TBA

**Describe alternatives you've considered**
TBA

**Additional context**
TBA

**Comment by BorisYourich** [comment]
I was thinking about writing a utility(possibly in C++) that would parse the bam file and check for alignments with high number of mismatches from both ends (up to a given number of nucleotides N) and if the aligned read contains high percentage of adenine(A%)  then it would be qualified as containing a polyA tail and the alignment possibly pasted into a separate polyA_reads.bam file and in the htsinfer we would increment the counter or something... Wanted to ask If it makes sense before I start implementing, let me know if this kind of implementation would be appropriate. The parameters N and A are up to debate.

**Comment by uniqueg** [comment]
For context: The use case that motivates this feature is that people running RNA-seq pipelines want to know if they should include a step to remove polyA tails prior to mapping. So what they would need is a kind of `True` / `False` answer.

Now, a library that would benefit from such processing is one that (a) has been prepared with a protocol that preserves and (b) has a sizeable (whatever that means; but we can parametrize that) fraction of reads that have polyA tails in them.

That being said, the simplest implementation I can think of is to run `cutadapt` with `-a "A{100}"` or `-a "A{10}N{90}"` (see https://cutadapt.readthedocs.io/en/v1.8.1/recipes.html#trimming-poly-a-tails) and parsing the report (is the percentage of cleaved reads higher than our treshold)?

An improved version would do what you suggest: Map the reads first, allowing for soft clipping (possible, e.g., with `STAR` and the local alignments setting), and only analyze the soft-clipped parts of the reads. However, in that case you need (a) the organism, (b) a complete set of genome annotations for that organism (which version? where to get them from?).

So if you ask me, I would just go with the simple version that requires no real business logic. Less code to write, less code to test and maintain. Plus `cutadapt` is already pretty fast.

**Comment by uniqueg** [comment]
Fixed by #102
