### ISSUE TITLE
pytest issue on macOS Big Sur

### ISSUE THREAD

**Issue by BorisYourich** [zavolanlab/htsinfer#93]
**Describe the bug**
Os-dependent issue when testing the installation of development/testing dependencies.
Error is: `htsinfer.exceptions.StarProblem: Failed to create STAR index`
If solved then: `htsinfer.exceptions.StarProblem: Failed to generate STAR alignments`

**To Reproduce**

1. Use computer with macOS Big Sur and Miniconda(4.12.0) installation.
2. Follow the Installation tutorial for `htsinfer`.

**Expected behavior**
To pass all tests.

**Desktop (please complete the following information):**

- OS: macOS Big Sur

**Additional context**
The problem solution is trivial although not up to me to decide 
if it should be a part of the codebase.

**Solution**
In file `htsinfer/htsinfer/get_read_orientation.py` (dev branch)
Add `index_dir.mkdir(parents=True, exist_ok=True)` in line 255.
Add `Path(out_dir).mkdir(parents=True, exist_ok=True)` in line 319.

**Comment by uniqueg** [comment]
Thanks @BorisYourich - would be happy to accept a PR for that :)

**Comment by rohank63** [comment]
I just want to add, I was also having the same issue, as I have big sure too, but later it got fixed by installing STAR through the official github repo and then make STAR.

**Comment by uniqueg** [comment]
So is this an issue of the STAR version for Mac on Conda? Perhaps we could just try to bump STAR in the requirements, then. Latest version on Anaconda seems to be `2.7.10a`: https://anaconda.org/search?q=star
